package com.smartfile.api;

/**
 * Exception generated by the library. Contains <code>int status</code> field
 * which stores server status code in case of error server error, or 0 in case
 * of internal error.
 */
public class SmartFileException extends Exception {
    private int status = 0;

    public SmartFileException(String error, int status) {
        super(error);
        this.status = status;
    }

    @Override
    public String toString() {
        return this.getMessage();
    }

    public int getStatus() {
        return this.status;
    }
}
